server:
  port: 8090
  servlet:
    context-path: /api
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-dq4lwxcu.sql.tencentcdb.com:20065/chatMgmt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Ican_2023
  # MyBatis配置
mybatis:
  mapper-locations: com/chat/mapper/*Mapper.xml

user:
  uname: fyt

# 阿里云OSS
oss:
  file:
    endpoint: oss-cn-shanghai.aliyuncs.com # 对应公网endpoint地址
    accessKeyId: LTAI5tKVVW5Py6qMWKsTzehS
    accessKeySecret: jwETu9qJJweBBUAb3apEQyC0yhGkwB
    bucketName: oss-chuanbin
    folder: helloFile #保存文件夹路径


chatgpt:
  model: gpt-3.5-turbo # 默认模型
  endpoint: https://api.openai.com/v1/chat/completions
  token:  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
  retries: 2 # 重新请求的次数
  maxTokens: 50 # 最大 Token 数
  temperature: 0.5 # 该值越大每次返回的结果越随机，即相似度越小

  # 默认模型
  # 重新请求的次数
  # 最大 Token 数
  # 该值越大每次返回的结果越随机，即相似度越小
#  text-davinci-003


switch:
  ifCheck: ifCheck
